import { computed, ref } from 'vue'
import { defineStore } from 'pinia'

const translations = {
  pt: {
    'header.about': 'SOBRE',
    'header.contact': 'CONTATO',
    'header.projects': 'PROJETOS',
    'footer.developedBy': 'Desenvolvido por Manu Hostin.',
    'about.bio1': 'Designer e diretora de arte com mais de 15 anos de experiência na área criativa, atuando com comunicação visual, ilustração e motion design.',
    'about.bio2': 'Desenvolvo materiais digitais e peças audiovisuais que unem estética, clareza e impacto visual, com atenção aos detalhes técnicos e consistência nas entregas.',
    'about.bio3': 'Com perfil multidisciplinar e fluência em inglês, tenho experiência em colaborar com equipes e projetos de diferentes áreas e escalas, garantindo resultados visualmente sólidos, criativos e alinhados ao propósito de cada marca.',
    'about.card1Title': 'Direção de Arte & Criação Visual',
    'about.card1Text': 'Visão estética apurada, atenção aos detalhes e forte domínio dos critérios técnicos e criativos. Tenho facilidade em tomar decisões visuais com segurança.',
    'about.card2Title': 'Comunicação com Clientes',
    'about.card2Text': 'Experiência em traduzir ideias em propostas visuais claras e bem argumentadas. Tenho boa escuta e empatia para criar conexões de confiança.',
    'about.card3Title': 'Agilidade Técnica & Trabalho em Equipes',
    'about.card3Text': 'Tenho domínio sólido de ferramentas e softwares e aprendo com facilidade o necessário para o avanço do projeto. No trabalho em equipe, atuo com atenção e abertura, incentivando trocas construtivas e garantindo entregas bem alinhadas e de qualidade.',
    'about.softwares': 'Softwares Dominados',
    'contact.title': 'Contato',
    'contact.intro': 'Me envie uma mensagem para orçamentos, parcerias ou dúvidas. Você pode falar comigo pelo formulário, e-mail, WhatsApp ou Instagram.',
    'contact.formTitle': 'Formulário de Contato',
    'contact.nameLabel': 'Nome',
    'contact.namePlaceholder': 'Seu nome',
    'contact.emailLabel': 'E-mail',
    'contact.emailPlaceholder': 'seuemail@exemplo.com',
    'contact.messageLabel': 'Mensagem',
    'contact.messagePlaceholder': 'Escreva sua mensagem',
    'contact.sending': 'Enviando...',
    'contact.submit': 'Enviar mensagem',
    'contact.otherChannels': 'Outros Canais',
    'contact.statusSuccess': 'MENSAGEM ENVIADA COM SUCESSO!',
    'contact.statusError': 'Não foi possível enviar agora. Tente novamente.',
    'contact.statusConnection': 'Erro de conexão. Tente novamente.',
    'home.tabs.digitalIllustration': 'Ilustração Digital',
    'home.tabs.videos': 'Vídeos',
    'home.tabs.branding': 'Branding',
    'home.tabs.design': 'Design Gráfico',
    'home.imagesCount': '{count} imagens',
    'home.noFolderFound': 'Nenhuma pasta encontrada para {category}.',
    'home.emptyCategory': 'Categoria pronta para receber conteúdo.',
    'home.illustrationEmpty': 'Nenhuma imagem encontrada para Ilustração Digital.',
    'home.close': 'Fechar',
    'home.viewFullVideo': 'Ver vídeo completo {number}',
    'home.art': 'Arte',
    'home.descriptionUpdating': 'Descrição em breve.',
    'home.projects.121shop.title': '121 SHOP',
    'home.projects.121shop.description': 'Apresentação comercial da 121 Smart Shop com peças para feed, stories e materiais institucionais.',
    'home.projects.acocerto.title': 'AcoCerto',
    'home.projects.acocerto.description': 'Campanhas e materiais visuais para comunicação da AcoCerto em diferentes formatos digitais.',
    'home.projects.cardionutri.title': 'CardioNutri',
    'home.projects.cardionutri.description': 'Conteúdos visuais para comunicação de serviços e autoridade da marca CardioNutri.',
    'home.projects.cbg.title': 'CBG',
    'home.projects.cbg.description': 'Peças de identidade e publicações para fortalecimento da presença digital da marca CBG.',
    'home.projects.hapo.title': 'HAPO',
    'home.projects.hapo.description': 'Materiais gráficos para campanhas e comunicação de marca com foco em clareza visual.',
    'home.projects.krenke.title': 'KRENKE',
    'home.projects.krenke.description': 'Conjunto de artes para posicionamento de marca e divulgação de produtos.',
    'home.projects.ladimas.title': 'LADIMAS',
    'home.projects.ladimas.description': 'Design de comunicação para redes sociais e materiais promocionais da Ladimas.',
    'home.projects.logcerto.title': 'LOGCERTO',
    'home.projects.logcerto.description': 'Coleção de peças criativas para comunicação digital e fortalecimento institucional.',
    'home.projects.menegotti.title': 'MENEGOTTI',
    'home.projects.menegotti.description': 'Materiais visuais para campanhas sazonais, institucionais e promocionais da Menegotti.',
    'home.projects.mesaville.title': 'MESAVILLE',
    'home.projects.mesaville.description': 'Artes para feed e campanhas de conversão com linguagem visual consistente.',
    'home.projects.multivisi.title': 'MULTIVISI',
    'home.projects.multivisi.description': 'Peças de comunicação visual para performance digital e reconhecimento da marca.',
    'home.projects.soliduz.title': 'SOLIDUZ',
    'home.projects.soliduz.description': 'Identidade e peças gráficas para comunicação de serviços e captação de clientes.',
    'home.projects.connectbox.title': 'CONNECT BOX',
    'home.projects.connectbox.description': 'Projetos de branding e comunicação visual para posicionamento da Connect Box.',
    'home.projects.domen.title': 'DOMEN',
    'home.projects.domen.description': 'Peças de marca e comunicação institucional para fortalecer a presença da Domen.',
    'home.projects.tricostura.title': 'TRICOSTURA',
    'home.projects.tricostura.description': 'Materiais de branding aplicados em redes sociais e campanhas de divulgação.',
    'home.projects.fluxogama.title': 'FLUXOGAMA',
    'home.projects.fluxogama.description': 'Coleção visual de branding e comunicação para consolidação da identidade Fluxogama.',
    'home.projects.ilustracaodigital.title': 'Ilustração Digital',
    'home.projects.ilustracaodigital.description': 'Coleção de artes autorais e estudos visuais desenvolvidos em ilustração digital utilizando Photoshop, muitos no Instituto Belas Artes para ensino de alunos ou exposições.',
    'home.projects.rdsummit.title': 'RD Summit',
    'home.projects.rdsummit.description': 'Coleção de GIFs e motion pieces criados para campanhas e divulgação do RD Summit.',
    'home.projects.mercadaodosoculos.title': 'Mercadão dos Óculos',
    'home.projects.mercadaodosoculos.description': 'Animações promocionais desenvolvidas para campanhas sazonais da rede.',
    'home.projects.univille.title': 'Univille',
    'home.projects.univille.description': 'Sequência de vídeos curtos em GIF para divulgação institucional e promocional.',
    'home.projects.121shop.title': '121 Shop',
    'home.projects.121shop.description': 'Vídeos e GIFs de apoio comercial e divulgação de serviços.',
  },
  en: {
    'header.about': 'ABOUT',
    'header.contact': 'CONTACT',
    'header.projects': 'PROJECTS',
    'footer.developedBy': 'Developed by Manu Hostin.',
    'about.bio1': 'Designer and art director with over 15 years of experience in the creative field, working with visual communication, illustration, and motion design.',
    'about.bio2': 'I develop digital materials and audiovisual pieces that combine aesthetics, clarity, and visual impact, with careful attention to technical detail and consistency in delivery.',
    'about.bio3': 'With a multidisciplinary profile and fluency in English, I have experience collaborating with teams and projects of different sizes and scopes, ensuring visually strong, creative results aligned with each brand’s purpose.',
    'about.card1Title': 'Art Direction & Visual Creation',
    'about.card1Text': 'Refined aesthetic vision, attention to detail, and strong command of technical and creative criteria. I can make visual decisions with confidence.',
    'about.card2Title': 'Client Communication',
    'about.card2Text': 'Experience translating ideas into clear, well-argued visual proposals. I listen closely and build trust through empathy.',
    'about.card3Title': 'Technical Agility & Teamwork',
    'about.card3Text': 'I have solid command of tools and software and learn what is needed quickly to move projects forward. In teamwork, I act with openness and attention, encouraging constructive exchange and high-quality delivery.',
    'about.softwares': 'Software Expertise',
    'contact.title': 'Contact',
    'contact.intro': 'Send me a message for quotes, partnerships, or questions. You can reach me through the form, email, WhatsApp, or Instagram.',
    'contact.formTitle': 'Contact Form',
    'contact.nameLabel': 'Name',
    'contact.namePlaceholder': 'Your name',
    'contact.emailLabel': 'E-mail',
    'contact.emailPlaceholder': 'youremail@example.com',
    'contact.messageLabel': 'Message',
    'contact.messagePlaceholder': 'Write your message',
    'contact.sending': 'Sending...',
    'contact.submit': 'Send message',
    'contact.otherChannels': 'Other Channels',
    'contact.statusSuccess': 'MESSAGE SENT SUCCESSFULLY!',
    'contact.statusError': 'It was not possible to send it right now. Please try again.',
    'contact.statusConnection': 'Connection error. Please try again.',
    'home.tabs.digitalIllustration': 'Digital Illustration',
    'home.tabs.videos': 'Videos',
    'home.tabs.branding': 'Branding',
    'home.tabs.design': 'Graphic Design',
    'home.imagesCount': '{count} images',
    'home.noFolderFound': 'No folders found for {category}.',
    'home.emptyCategory': 'Category ready to receive content.',
    'home.illustrationEmpty': 'No images found for Digital Illustration.',
    'home.close': 'Close',
    'home.viewFullVideo': 'View full video {number}',
    'home.art': 'Art',
    'home.descriptionUpdating': 'Description coming soon.',
    'home.projects.121shop.title': '121 SHOP',
    'home.projects.121shop.description': 'Commercial presentation of 121 Smart Shop with pieces for feed, stories, and institutional materials.',
    'home.projects.acocerto.title': 'AcoCerto',
    'home.projects.acocerto.description': 'Campaigns and visual materials for AcoCerto communication in different digital formats.',
    'home.projects.cardionutri.title': 'CardioNutri',
    'home.projects.cardionutri.description': 'Visual content for service communication and authority building for the CardioNutri brand.',
    'home.projects.cbg.title': 'CBG',
    'home.projects.cbg.description': 'Identity pieces and publications to strengthen the digital presence of the CBG brand.',
    'home.projects.hapo.title': 'HAPO',
    'home.projects.hapo.description': 'Graphic materials for campaigns and brand communication focused on visual clarity.',
    'home.projects.krenke.title': 'KRENKE',
    'home.projects.krenke.description': 'A set of artworks for brand positioning and product promotion.',
    'home.projects.ladimas.title': 'LADIMAS',
    'home.projects.ladimas.description': 'Communication design for social media and promotional materials for Ladimas.',
    'home.projects.logcerto.title': 'LOGCERTO',
    'home.projects.logcerto.description': 'Collection of creative pieces for digital communication and institutional strengthening.',
    'home.projects.menegotti.title': 'MENEGOTTI',
    'home.projects.menegotti.description': 'Visual materials for seasonal, institutional, and promotional campaigns for Menegotti.',
    'home.projects.mesaville.title': 'MESAVILLE',
    'home.projects.mesaville.description': 'Feed art and conversion campaigns with consistent visual language.',
    'home.projects.multivisi.title': 'MULTIVISI',
    'home.projects.multivisi.description': 'Visual communication pieces for digital performance and brand recognition.',
    'home.projects.soliduz.title': 'SOLIDUZ',
    'home.projects.soliduz.description': 'Identity and graphic pieces for service communication and customer acquisition.',
    'home.projects.connectbox.title': 'CONNECT BOX',
    'home.projects.connectbox.description': 'Branding and visual communication projects for positioning Connect Box.',
    'home.projects.domen.title': 'DOMEN',
    'home.projects.domen.description': 'Brand pieces and institutional communication to strengthen Domen’s presence.',
    'home.projects.tricostura.title': 'TRICOSTURA',
    'home.projects.tricostura.description': 'Branding materials applied across social media and promotional campaigns.',
    'home.projects.fluxogama.title': 'FLUXOGAMA',
    'home.projects.fluxogama.description': 'Visual branding and communication collection to consolidate the Fluxogama identity.',
    'home.projects.ilustracaodigital.title': 'Digital Illustration',
    'home.projects.ilustracaodigital.description': 'Collection of original artwork and visual studies created in digital illustration using Photoshop, many produced at Instituto Belas Artes for teaching students or exhibitions.',
    'home.projects.rdsummit.title': 'RD Summit',
    'home.projects.rdsummit.description': 'Collection of GIFs and motion pieces created for RD Summit campaigns and promotion.',
    'home.projects.mercadaodosoculos.title': 'Mercadão dos Óculos',
    'home.projects.mercadaodosoculos.description': 'Promotional animations developed for seasonal campaigns of the network.',
    'home.projects.univille.title': 'Univille',
    'home.projects.univille.description': 'Short GIF video sequences for institutional and promotional communication.',
    'home.projects.121shop.title': '121 Shop',
    'home.projects.121shop.description': 'Videos and GIFs supporting commercial promotion and service communication.',
  },
}

export const useLanguageStore = defineStore('language', () => {
  const currentLanguage = ref(
    typeof window !== 'undefined' ? window.localStorage.getItem('portfolio-language') || 'pt' : 'pt'
  )

  const isEnglish = computed(() => currentLanguage.value === 'en')

  function setLanguage(lang) {
    currentLanguage.value = lang

    if (typeof window !== 'undefined') {
      window.localStorage.setItem('portfolio-language', lang)
    }
  }

  function t(key, params = {}) {
    const value = translations[currentLanguage.value]?.[key] || translations.pt[key] || key

    return Object.entries(params).reduce((acc, [param, replacement]) => {
      return acc.replace(`{${param}}`, replacement)
    }, value)
  }

  return {
    currentLanguage,
    isEnglish,
    setLanguage,
    t,
  }
})
